services:
  app:
    build:
      context: .
    image: kleapi
    container_name: kleapi
    ports:
      - "8081:8001"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - laravel-network
    command: php artisan serve --host=0.0.0.0 --port=8001

  db:
    image: mysql:8
    container_name: kleapi-db
    environment:
      MYSQL_DATABASE: kleapi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true
    driver: bridge

volumes:
  db_data:
